"""
Sandboxed-ish execution of Python code generated by the agent.

This is NOT a security sandbox against a truly malicious actor - it's a
practical safety net so that code the LLM writes (which can be wrong,
infinite-loop, or crash) can't take down the ByteFlow process itself,
and can't run forever. It does this by:

  - Running the code in a separate `python` subprocess, not in-process
  - Enforcing a wall-clock timeout (default 10s), killing the process if exceeded
  - Capturing stdout/stderr separately instead of letting exceptions propagate
  - Running with cwd set to a fresh temp directory, so file writes can't
    casually clobber the user's working directory

It does NOT stop code from reading/writing files it has permission to
access, or making network calls if your machine allows it. Don't run
code from a source you don't trust at all without a real sandbox
(containers, gVisor, etc). For an offline personal coding assistant
generating its own code, this is a reasonable, lightweight safety net.
"""

import subprocess
import sys
import tempfile
import os


class ExecutionResult:
    def __init__(self, stdout, stderr, returncode, timed_out=False):
        self.stdout = stdout
        self.stderr = stderr
        self.returncode = returncode
        self.timed_out = timed_out

    @property
    def success(self):
        return self.returncode == 0 and not self.timed_out

    def __repr__(self):
        return (
            f"ExecutionResult(success={self.success}, "
            f"returncode={self.returncode}, timed_out={self.timed_out})"
        )

    def format(self):
        """Human-readable summary, suitable for showing to a user."""
        parts = []
        if self.timed_out:
            parts.append("[Execution timed out]")
        if self.stdout:
            parts.append(f"--- stdout ---\n{self.stdout}")
        if self.stderr:
            parts.append(f"--- stderr ---\n{self.stderr}")
        if not parts:
            parts.append("(no output)")
        return "\n".join(parts)


def run_python_code(code, timeout=10):
    """
    Run `code` as a standalone Python script in a subprocess.

    Returns an ExecutionResult. Never raises for normal code errors -
    those show up in .stderr with returncode != 0. Only raises for
    unexpected environment issues (e.g. python interpreter not found).
    """
    with tempfile.TemporaryDirectory() as tmp_dir:
        script_path = os.path.join(tmp_dir, "snippet.py")
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(code)

        try:
            proc = subprocess.run(
                [sys.executable, script_path],
                cwd=tmp_dir,
                capture_output=True,
                text=True,
                timeout=timeout,
                stdin=subprocess.DEVNULL,
            )
            stderr = proc.stderr
            if proc.returncode != 0 and "EOFError" in stderr and "input(" in code:
                stderr += (
                    "\n[Note: this sandbox runs code non-interactively with no "
                    "stdin, so input() always raises EOFError immediately. "
                    "Rewrite the snippet with fixed sample values instead of "
                    "calling input().]"
                )
            return ExecutionResult(
                stdout=proc.stdout,
                stderr=stderr,
                returncode=proc.returncode,
            )
        except subprocess.TimeoutExpired as e:
            return ExecutionResult(
                stdout=e.stdout or "",
                stderr=(e.stderr or "") + f"\n[Timed out after {timeout}s]",
                returncode=-1,
                timed_out=True,
            )
